"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { useEffect, useState } from "react";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <html lang="en">
      <Head>
        <title>Pump Sui</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        {mounted ? (
          <ThemeProvider attribute="class" defaultTheme="dark">
            {children}
          </ThemeProvider>
        ) : (
          <div className="bg-black"></div>
        )}
      </body>
    </html>
  );
}
